name: Deploy Laravel to Ubuntu

on:
  push:
    branches: [ "develop" ]

jobs:
  Dev-Deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
    - name: Deploy to Ubuntu
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@52.198.121.46 'cd /var/www/html/khufu-back-end && chmod 775 deploy.sh && ./deploy.sh'